name = "minimovie-ui"
main = "@astrojs/cloudflare/entrypoints/server"
compatibility_date = "2025-05-21"
compatibility_flags = ["nodejs_compat"]

[vars]
LOG_LEVEL = "INFO"
API_BASE_URL = "https://api.minimovie.info"

[[routes]]
pattern = "minimovie.info"
custom_domain = true

[[routes]]
pattern = "www.minimovie.info"
custom_domain = true

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true
